fragment PostParts on Post {
  __typename
  title
  metaDescription
  metaKeywords
  excerpt
  date
  author
  authorTitle
  readTime
  category
  tags
  featured
  image
  body
  schemaMarkup {
    __typename
    type
    headline
    datePublished
    dateModified
    authorName
    publisherName
    publisherLogo
    description
  }
}

fragment HomePageParts on HomePage {
  __typename
  title
  metaDescription
  metaKeywords
  heroHeading
  heroSubheading
  heroImage
  schemaMarkup {
    __typename
    type
    name
    description
    url
    image
  }
  stats {
    __typename
    value
    label
  }
  features {
    __typename
    title
    description
    icon
  }
  valueCards {
    __typename
    title
    description
    icon
  }
  testimonial {
    __typename
    quote
    author
    role
    company
  }
  industries {
    __typename
    name
  }
  teamMembers {
    __typename
    name
    title
    bio
    image
  }
}

fragment PageParts on Page {
  __typename
  title
  metaDescription
  metaKeywords
  description
  body
  schemaMarkup {
    __typename
    type
    name
    description
    url
    image
  }
}

fragment ApproachPageParts on ApproachPage {
  __typename
  title
  metaDescription
  metaKeywords
  heroHeading
  heroSubheading
  schemaMarkup {
    __typename
    type
    name
    description
    url
    image
  }
  approachSteps {
    __typename
    title
    description
    stepNumber
  }
  principles {
    __typename
    title
    description
    icon
  }
}

fragment ResultsPageParts on ResultsPage {
  __typename
  title
  metaDescription
  metaKeywords
  heroHeading
  heroSubheading
  schemaMarkup {
    __typename
    type
    name
    description
    url
    image
  }
  metrics {
    __typename
    value
    label
    icon
  }
  caseStudies {
    __typename
    title
    challenge
    approach
    outcome
    client
    clientRole
    company
  }
  achievements {
    __typename
    text
  }
  testimonial {
    __typename
    quote
    author
    role
    company
  }
}

fragment ServicesPageParts on ServicesPage {
  __typename
  title
  metaDescription
  metaKeywords
  heroHeading
  heroSubheading
  schemaMarkup {
    __typename
    type
    name
    description
    url
    image
  }
  services {
    __typename
    title
    description
    icon
  }
}

fragment TeamPageParts on TeamPage {
  __typename
  title
  metaDescription
  metaKeywords
  heroHeading
  heroSubheading
  schemaMarkup {
    __typename
    type
    name
    description
    url
    image
  }
  teamMembers {
    __typename
    name
    title
    bio
    image
    email
    phone
    linkedin
  }
}

fragment ContactPageParts on ContactPage {
  __typename
  title
  metaDescription
  metaKeywords
  heroHeading
  heroSubheading
  schemaMarkup {
    __typename
    type
    name
    description
    url
    image
  }
  offices {
    __typename
    city
    address
    phone
    email
  }
  contactForm {
    __typename
    heading
    subheading
    successMessage
  }
}

fragment UpdatesPageParts on UpdatesPage {
  __typename
  title
  metaDescription
  metaKeywords
  heroHeading
  heroSubheading
  schemaMarkup {
    __typename
    type
    name
    description
    url
    image
  }
  featuredCategories {
    __typename
    name
    description
  }
}
