[build]
  command = "./build.sh"
  publish = "dist"
  node_version = "18.19.1" # Trigger rebuild

[build.environment]
  NODE_VERSION = "18.19.1"
  NPM_VERSION = "10.2.4"
  SECRETS_SCAN_OMIT_KEYS = "AUTH0_AUDIENCE,AUTH0_CLIENT_ID"
  NPM_FLAGS = "--legacy-peer-deps --force"
  NODE_OPTIONS = "--max-old-space-size=4096"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "@netlify/plugin-emails"

# Invitation redirects removed - no longer using Netlify Identity

# Admin redirects removed - will be replaced with a new solution

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Ensure PDF files are accessible
[[redirects]]
  from = "/files/*"
  to = "/files/:splat"
  status = 200

# Ensure sitemap.xml is accessible
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/admin/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://identity.netlify.com; style-src 'self'; img-src 'self' data:; connect-src 'self' https://identity.netlify.com; font-src 'self'; object-src 'none'; media-src 'self'; frame-src 'self' https://identity.netlify.com; worker-src 'self'; frame-ancestors 'none'; form-action 'self'; base-uri 'self'; manifest-src 'self'"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Permitted-Cross-Domain-Policies = "none"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-origin"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' data: https://identity.netlify.com https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline' https://*.unsplash.com https://fonts.googleapis.com; img-src 'self' data: https://www.google-analytics.com https://*.unsplash.com https://images.unsplash.com https://res.cloudinary.com; connect-src 'self' https://www.google-analytics.com https://fonts.googleapis.com https://fonts.gstatic.com; font-src 'self' https://fonts.gstatic.com data:; frame-ancestors 'none'; upgrade-insecure-requests; worker-src 'self' blob:;"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Set correct MIME types for JavaScript files
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/assets/*.ts"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/assets/*.tsx"
  [headers.values]
    Content-Type = "application/javascript"


[[edge_functions]]
function = "hello"
path = "/test"
