[build]
  command = "npm run build"
  publish = "dist"
  node_version = "18.19.1"

[build.environment]
  NODE_VERSION = "18.19.1"
  NPM_VERSION = "10.2.4"
  SECRETS_SCAN_OMIT_KEYS = "AUTH0_AUDIENCE,AUTH0_CLIENT_ID"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "@netlify/plugin-emails"

[[redirects]]
  from = "/"
  to = "/invite-help.html"
  status = 302
  force = true
  conditions = {Query = [["invite_token", ""]]}

[[redirects]]
  from = "/"
  to = "/invite-help.html"
  status = 302
  force = true
  conditions = {Hash = ["#invite_token=*"]}

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://www.googletagmanager.com https://www.google-analytics.com 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://*.unsplash.com https://fonts.googleapis.com; style-src-elem 'self' 'unsafe-inline' https://*.unsplash.com https://fonts.googleapis.com; style-src-attr 'self' 'unsafe-inline' https://*.unsplash.com; img-src 'self' data: https://www.google-analytics.com https://*.unsplash.com https://images.unsplash.com; connect-src 'self' https://www.google-analytics.com; font-src 'self' https://fonts.gstatic.com; frame-ancestors 'none'; upgrade-insecure-requests;"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
