[build]
  command = "npm run build"
  publish = "dist"
  node_version = "18.19.1" # Trigger rebuild

[build.environment]
  NODE_VERSION = "18.19.1"
  NPM_VERSION = "10.2.4"
  SECRETS_SCAN_OMIT_KEYS = "AUTH0_AUDIENCE,AUTH0_CLIENT_ID"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "@netlify/plugin-emails"

# Invitation redirects removed - no longer using Netlify Identity

# Admin redirects removed - will be replaced with a new solution

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Ensure PDF files are accessible
[[redirects]]
  from = "/files/*"
  to = "/files/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/admin/*"
  [headers.values]
    Content-Security-Policy = "default-src * 'unsafe-inline' 'unsafe-eval'; script-src * 'unsafe-inline' 'unsafe-eval'; connect-src * 'unsafe-inline'; img-src * data: blob: 'unsafe-inline'; frame-src *; style-src * 'unsafe-inline';"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://identity.netlify.com https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' https://*.unsplash.com https://fonts.googleapis.com; img-src 'self' data: https://www.google-analytics.com https://*.unsplash.com https://images.unsplash.com https://res.cloudinary.com; connect-src 'self' https://www.google-analytics.com; font-src 'self' https://fonts.gstatic.com; frame-ancestors 'none'; upgrade-insecure-requests;"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"


[[edge_functions]]
function = "hello"
path = "/test"
