[[edge_functions]]
function = "hello"
path = "/test"

[functions]

  [functions.emails]
  included_files = [
    "./emails/**"
  ]

[build]
command = "npm run build:ci"
publish = "dist"
node_version = "18.19.1"

  [build.environment]
  NODE_VERSION = "18.19.1"
  NPM_VERSION = "10.2.4"
  SECRETS_SCAN_OMIT_KEYS = "AUTH0_AUDIENCE,AUTH0_CLIENT_ID"

[[plugins]]
package = "@netlify/plugin-lighthouse"

[[plugins]]
package = "@netlify/plugin-emails"

[[headers]]
for = "/*"

  [headers.values]
  X-Robots-Tag = "google-site-verification=m56tQG4npD-YUtq_2kRTIya2nveMVfw1iOYg-ome0jY"

[[headers]]
for = "/admin/*"

  [headers.values]
  Content-Security-Policy = "default-src 'self'; script-src 'self' https://identity.netlify.com; style-src 'self'; img-src 'self' data:; connect-src 'self' https://identity.netlify.com; font-src 'self'; object-src 'none'; media-src 'self'; frame-src 'self' https://identity.netlify.com; worker-src 'self'; frame-ancestors 'none'; form-action 'self'; base-uri 'self'; manifest-src 'self'"
  Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  X-Permitted-Cross-Domain-Policies = "none"
  Cross-Origin-Embedder-Policy = "require-corp"
  Cross-Origin-Opener-Policy = "same-origin"
  Cross-Origin-Resource-Policy = "same-origin"

[[headers]]
for = "/*"

  [headers.values]
  Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' data: https://identity.netlify.com https://www.googletagmanager.com https://www.google-analytics.com https://www.clarity.ms https://*.clarity.ms; style-src 'self' 'unsafe-inline' https://*.unsplash.com https://fonts.googleapis.com; img-src 'self' data: https://www.google-analytics.com https://*.unsplash.com https://images.unsplash.com https://res.cloudinary.com https://c.clarity.ms https://*.clarity.ms; connect-src 'self' https://www.google-analytics.com https://fonts.googleapis.com https://fonts.gstatic.com https://www.clarity.ms https://*.clarity.ms; font-src 'self' https://fonts.gstatic.com data:; frame-ancestors 'none'; upgrade-insecure-requests;"
  Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"

[[headers]]
for = "/*.js"

  [headers.values]
  Content-Type = "application/javascript"

[[headers]]
for = "/assets/*.js"

  [headers.values]
  Content-Type = "application/javascript"

[[headers]]
for = "/assets/*.ts"

  [headers.values]
  Content-Type = "application/javascript"

[[headers]]
for = "/assets/*.tsx"

  [headers.values]
  Content-Type = "application/javascript"

[[redirects]]
from = "/files/texas-legislative-influence-guide-2025.pdf"
to = "/files/texas-legislative-influence-guide-2025.html"
status = 301

[[redirects]]
from = "/files/healthcare-regulatory-changes.pdf"
to = "/files/healthcare-regulatory-changes.html"
status = 301

[[redirects]]
from = "/files/energy-grid-reliability.pdf"
to = "/files/energy-grid-reliability.html"
status = 301

[[redirects]]
from = "/files/texas-transportation-funding-outlook.pdf"
to = "/files/texas-transportation-funding-outlook.html"
status = 301

[[redirects]]
from = "/files/municipal-advocacy-strategies.pdf"
to = "/files/municipal-advocacy-strategies.html"
status = 301

[[redirects]]
from = "/files/telecommunications-regulatory-outlook.pdf"
to = "/files/telecommunications-regulatory-outlook.html"
status = 301

[[redirects]]
from = "/files/texas-legislative-calendar-2025.pdf"
to = "/files/texas-legislative-calendar-2025.html"
status = 301

[[redirects]]
from = "/files/water-infrastructure-funding.pdf"
to = "/files/water-infrastructure-funding.html"
status = 301

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/files/*"
to = "/files/:splat"
status = 200

[[redirects]]
from = "/sitemap.xml"
to = "/sitemap.xml"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[context]

  [context.production]

    [context.production.functions]

      [context.production.functions.emails]
      included_files = [
        "./emails/**"
      ]

  [context.main]

    [context.main.functions]

      [context.main.functions.emails]
      included_files = [
        "./emails/**"
      ]
