backend:
  name: github
  repo: ezhulati/capitol-insights
  branch: main
  auth_scope: repo
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: 'Upload "{{path}}"'
    deleteMedia: 'Delete "{{path}}"'

media_folder: "public/uploads" # Media will be stored in this directory
public_folder: "/uploads" # The src attribute for uploaded media

collections:
  # Home page content
  - name: "home"
    label: "Home Page"
    files:
      - name: "home"
        label: "Home Page Content"
        file: "content/home/index.mdx"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Hero Heading", name: "heroHeading", widget: "string"}
          - {label: "Hero Subheading", name: "heroSubheading", widget: "markdown"}
          - {label: "Hero Image", name: "heroImage", widget: "image"}
          - label: "Schema Markup"
            name: "schemaMarkup"
            widget: "object"
            fields:
              - {label: "Type", name: "type", widget: "string"}
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "URL", name: "url", widget: "string"}
              - {label: "Image", name: "image", widget: "image"}
          - label: "Stats"
            name: "stats"
            widget: "list"
            fields:
              - {label: "Value", name: "value", widget: "string"}
              - {label: "Label", name: "label", widget: "string"}
          - label: "Features"
            name: "features"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Icon", name: "icon", widget: "string"}
          - label: "Value Cards"
            name: "valueCards"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Icon", name: "icon", widget: "string"}
          - label: "Testimonial"
            name: "testimonial"
            widget: "object"
            fields:
              - {label: "Quote", name: "quote", widget: "text"}
              - {label: "Author", name: "author", widget: "string"}
              - {label: "Role", name: "role", widget: "string"}
              - {label: "Company", name: "company", widget: "string"}
          - label: "Industries"
            name: "industries"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
          - label: "Team Members"
            name: "teamMembers"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Bio", name: "bio", widget: "text"}
              - {label: "Image", name: "image", widget: "image"}
          - {label: "Body", name: "body", widget: "markdown"}

  # Blog posts/updates
  - name: "posts"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    extension: "mdx"
    format: "frontmatter"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Author Title", name: "authorTitle", widget: "string"}
      - {label: "Read Time", name: "readTime", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  # Services page
  - name: "services"
    label: "Services"
    files:
      - name: "services"
        label: "Services Page"
        file: "content/services/index.mdx"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Hero Heading", name: "heroHeading", widget: "string"}
          - {label: "Hero Subheading", name: "heroSubheading", widget: "markdown"}
          - {label: "Hero Image", name: "heroImage", widget: "image"}
          - {label: "Body", name: "body", widget: "markdown"}

  # Team page
  - name: "team"
    label: "Team"
    files:
      - name: "team"
        label: "Team Page"
        file: "content/team/index.mdx"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Hero Heading", name: "heroHeading", widget: "string"}
          - {label: "Hero Subheading", name: "heroSubheading", widget: "markdown"}
          - {label: "Hero Image", name: "heroImage", widget: "image"}
          - label: "Team Members"
            name: "teamMembers"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Bio", name: "bio", widget: "markdown"}
              - {label: "Image", name: "image", widget: "image"}
          - {label: "Body", name: "body", widget: "markdown"}

  # Approach page
  - name: "approach"
    label: "Approach"
    files:
      - name: "approach"
        label: "Approach Page"
        file: "content/approach/index.mdx"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Hero Heading", name: "heroHeading", widget: "string"}
          - {label: "Hero Subheading", name: "heroSubheading", widget: "markdown"}
          - {label: "Hero Image", name: "heroImage", widget: "image"}
          - {label: "Body", name: "body", widget: "markdown"}

  # Results page
  - name: "results"
    label: "Results"
    files:
      - name: "results"
        label: "Results Page"
        file: "content/results/index.mdx"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Hero Heading", name: "heroHeading", widget: "string"}
          - {label: "Hero Subheading", name: "heroSubheading", widget: "markdown"}
          - {label: "Hero Image", name: "heroImage", widget: "image"}
          - {label: "Body", name: "body", widget: "markdown"}

  # Contact page
  - name: "contact"
    label: "Contact"
    files:
      - name: "contact"
        label: "Contact Page"
        file: "content/contact/index.mdx"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Hero Heading", name: "heroHeading", widget: "string"}
          - {label: "Hero Subheading", name: "heroSubheading", widget: "markdown"}
          - {label: "Hero Image", name: "heroImage", widget: "image"}
          - {label: "Body", name: "body", widget: "markdown"}

  # Updates page
  - name: "updates"
    label: "Updates"
    files:
      - name: "updates"
        label: "Updates Page"
        file: "content/updates/index.mdx"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Hero Heading", name: "heroHeading", widget: "string"}
          - {label: "Hero Subheading", name: "heroSubheading", widget: "markdown"}
          - {label: "Hero Image", name: "heroImage", widget: "image"}
          - {label: "Body", name: "body", widget: "markdown"}
